apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "endpoints", "ingresses", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups:
    - extensions
  resources:
    - ingresses
  verbs:
    - get
    - update
    - create
    - list
    - patch
    - delete
    - watch